### ISSUE TITLE
test.err.stack sometimes is undefined

### ISSUE THREAD

**Issue by chenchaoyi** [TestArmada/magellan-xunit-reporter#3]
Due to the current implementation, stacktrace is parse through mocha json report from stdout, thus we have all the [limitations](https://github.com/TestArmada/magellan-xunit-reporter#limitation). We might look into a better way to get the stacktrace information from mocha.

**Comment by smccarthy** [comment]
@chenchaoyi I have --reporter json and using magellan 8.8.4 , and have --max_test_attempts set to 2 (I also tried max_test_attempts = 1). I see tests.err.stack is defined (from the console), but the mocha_report.xml still shows "undefined" for the stacktrace. I am using magellan-xunit-reporter 0.0.3 .

I did notice my test.stdout is an empty string.

Do you know if I am missing anything?

**Comment by chenchaoyi** [comment]
Hi @smccarthy , do you know why the stdout is empty? Currently this reporter depends on stdout to parse stacktrace: https://github.com/TestArmada/magellan-xunit-reporter/blob/2fb861575446596ab82f51a87c35ce56faaf2e39/src/reporter.js#L84-L91

What does your entire command and mocha.opts look like?

**Comment by smccarthy** [comment]
I wasn't able to reproduce the stdout as empty. However, I did find another issue. Here is a gist of my test.stdout
https://gist.github.com/smccarthy/71c6d2ce2882c597d0ce64d1da50b3ac (I printed that out from here : https://github.com/TestArmada/magellan-xunit-reporter/blob/2fb861575446596ab82f51a87c35ce56faaf2e39/src/reporter.js#L84 ).

These 3 lines don't get removed:
https://gist.github.com/smccarthy/71c6d2ce2882c597d0ce64d1da50b3ac#file-gistfile1-txt-L3-L5

or these ending lines:
https://gist.github.com/smccarthy/71c6d2ce2882c597d0ce64d1da50b3ac#file-gistfile1-txt-L76-L86

This causes an error with `testObject.err = JSON.parse(s).failures[0].err;` I edited a local copy of `addResult` to remove everything before the first `{` and everything after the last `}` . This won't always work tho I guess. Is there no way to access the raw JSON, without having to do a bunch of string manipulation on it?

**Comment by smccarthy** [comment]
@chenchaoyi I opened a PR to fix the issues I had. I remove everything before the JSON object, everything after the JSON object, and remove line breaks as well.

**Comment by chenchaoyi** [comment]
@smccarthy you are right, the current implementation by parsing stdout is just a temporary workaround. We'll be looking at a better way of pass through mocha tests error stack to Magellan.

Meanwhile, I merged your PR and published 0.0.4. Thanks for the improvement.

**Comment by smccarthy** [comment]
Awesome, thank you !
